// Generated by scripts/generate-online-registry.mjs
import { serverGame } from "../src/core/online";
import { onlineAdapter as game0 } from "../src/games/pageone/onlineAdapter";
export const games = Object.fromEntries([serverGame(game0)].map(game => [game.gameId, game]));
